### PR TITLE
add new keyword to list all namespaced custom objects

### PR DESCRIPTION
**Pull request by kutayy**
For namespaced custom objects, we only have 1 keyword to get a specific object by providing its name. Adding another keyword to list all namespaced custom objects.

### CODE REVIEW

**Review by Nilsty — APPROVED** [review]
LGTM

**Comment by Nilsty** [comment]
hmm... the test failure does not look related to the changes. @m-wcislo could you have a look, and maybe re-run the test?

**Comment by m-wcislo** [comment]
It fails from time to time, but now I cannot make it pass. Please disable the test, I created separate issue to investigate it.

**Comment by kutayy** [comment]
@m-wcislo I removed `other` tagging from the exec suite to disable.

**Pull request merged**
