### PR TITLE
add kw to query Kubernetes API health endpoints

### PR DESCRIPTION
**Pull request by mika-b**
Implements #21

### CODE REVIEW

**Review by m-wcislo — COMMENTED** [review]
Thanks for your contribution. There is already PR addressing #21, but you could add your extra functionality (endpoint and verbosity handling on top of it) + for example support for individual tests and exclusions as in https://kubernetes.io/docs/reference/using-api/health-checks/?

If that is is ok with you we could merge it after #40 is merged.

**Comment by mika-b** [comment]
Rebased and updated. Hows that?

**Review by Nilsty — CHANGES_REQUESTED** [review]
Super nice! I really like those templated test cases.
Would you mind adding this PR to the changelog?
https://github.com/devopsspiral/KubeLibrary/blob/master/CHANGELOG.md

**Comment by mika-b** [comment]
Changelog update.

**Comment by mika-b** [comment]
Also added prerelease  tag.

**Review by Nilsty — APPROVED** [review]

**Pull request merged**
